<a href="https://colab.research.google.com/github/Mayurezh/AI-ML-PROJECT/blob/main/Heatwave_Prediction_MLOps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Part A — Machine Learning**

In [ ]:
!pip install -q mlflow scikit-learn pandas matplotlib

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.0/50.0 kB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 2.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.3/44.3 kB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 68.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 60.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 30.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.7/268.7 kB 16.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.8/148.8 kB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.4/228.4 kB 15.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.5/136.5 kB 10.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.6/144.6 kB 10.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 45.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 222.8/222.8 kB 16.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.0/216.0 kB 16.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 3.1 MB/s eta 0:00:00

In [ ]:
import pandas as pd
data = pd.DataFrame({
"max_temp":[38,40,43,45,36,42,39,44,41,46,37,43,45,39,41,47,38,44,42,46],
"min_temp":[27,28,30,31,26,29,27,30,28,32,26,30,31,27,29,33,27,31,29,32],
"humidity":[65,60,55,50,70,58,68,52,62,48,72,56,49,66,59,45,69,51,57,47],
"wind_speed":[12,10,8,7,15,9,11,8,10,6,14,8,7,12,9,5,13,7,9,6],
"previous_temp":[37,39,42,44,35,41,38,43,40,45,36,42,44,38,40,46,37,43,41,45],
"heatwave":[0,0,1,1,0,1,0,1,0,1,0,1,1,0,0,1,0,1,1,1]
})
data.head()

   max_temp  min_temp  humidity  wind_speed  previous_temp  heatwave
0        38        27        65          12             37         0
1        40        28        60          10             39         0
2        43        30        55           8             42         1
3        45        31        50           7             44         1
4        36        26        70          15             35         0

In [ ]:
data.info()
data.describe()
data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   max_temp       20 non-null     int64
 1   min_temp       20 non-null     int64
 2   humidity       20 non-null     int64
 3   wind_speed     20 non-null     int64
 4   previous_temp  20 non-null     int64
 5   heatwave       20 non-null     int64
dtypes: int64(6)
memory usage: 1.1 KB

max_temp         0
min_temp         0
humidity         0
wind_speed       0
previous_temp    0
heatwave         0
dtype: int64

In [ ]:
X=data[["max_temp","min_temp","humidity","wind_speed","previous_temp"]]
y=data["heatwave"]

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model=RandomForestClassifier(n_estimators=100,max_depth=5,random_state=42)
model.fit(X_train,y_train)

RandomForestClassifier(max_depth=5, random_state=42)

In [ ]:
from sklearn.metrics import accuracy_score
y_pred=model.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 1.0

# **Part B — ML FLOW**

In [ ]:
import mlflow
import mlflow.sklearn

In [ ]:
mlflow.set_experiment("Heatwave Prediction")

2026/09/20 16:40:50 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/09/20 16:40:50 INFO mlflow.store.db.utils: Updating database tables
2026/09/20 16:40:58 INFO mlflow.tracking.fluent: Experiment with name 'Heatwave Prediction' does not exist. Creating a new experiment.

<Experiment: artifact_location='/content/mlruns/1', creation_time=1789922458279, effective_trace_archival_retention=None, experiment_id='1', last_update_time=1789922458279, lifecycle_stage='active', name='Heatwave Prediction', tags={}, trace_location=None, workspace='default'>

In [ ]:
def run_experiment(n_estimators, max_depth):
  with mlflow.start_run():
    model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    mlflow.log_param("n_estimators", n_estimators)
    mlflow.log_param("max_depth", max_depth)
    mlflow.log_metric("accuracy", accuracy)
    mlflow.sklearn.log_model(model, "heatwave_model", skops_trusted_types=["sklearn.tree._tree.Tree"])
    print(f"n_estimators={n_estimators}, max_depth={max_depth} -> Accuracy: {accuracy}")
    return model, accuracy

In [ ]:
model1, acc1 = run_experiment(n_estimators=50, max_depth=3)
model2, acc2 = run_experiment(n_estimators=100, max_depth=5)
model3, acc3 = run_experiment(n_estimators=200, max_depth=10)

2026/09/20 16:43:04 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

n_estimators=50, max_depth=3 -> Accuracy: 1.0

2026/09/20 16:43:18 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

n_estimators=100, max_depth=5 -> Accuracy: 1.0

2026/09/20 16:43:30 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

n_estimators=200, max_depth=10 -> Accuracy: 1.0

In [ ]:
results = {
    "Run1 (50,3)": (model1, acc1),
    "Run2 (100,5)": (model2, acc2),
    "Run3 (200,10)": (model3, acc3),
}
best_run_name = max(results, key=lambda k: results[k][1])
best_model, best_accuracy = results[best_run_name]
print(f"Best run: {best_run_name} with accuracy {best_accuracy}")

Best run: Run1 (50,3) with accuracy 1.0

In [ ]:
runs_df = mlflow.search_runs()
runs_df[["params.n_estimators", "params.max_depth", "metrics.accuracy"]]

  params.n_estimators params.max_depth  metrics.accuracy
0                 200               10               1.0
1                 100                5               1.0
2                  50                3               1.0
3                  50                3               1.0
4                  50                3               1.0
5                 100                5               1.0

# Part C — ML OPS

In [ ]:
import joblib

joblib.dump(best_model, "heatwave_model.pkl")

print("Model saved successfully as heatwave_model.pkl")

Model saved successfully as heatwave_model.pkl

In [ ]:
import joblib
import pandas as pd

# Load trained model
model = joblib.load("heatwave_model.pkl")

def predict_heatwave(max_temp, min_temp, humidity, wind_speed, previous_temp):

    input_data = pd.DataFrame(
        [[max_temp, min_temp, humidity, wind_speed, previous_temp]],
        columns=[
            "max_temp",
            "min_temp",
            "humidity",
            "wind_speed",
            "previous_temp"
        ]
    )

    prediction = model.predict(input_data)[0]

    return "Heatwave" if prediction == 1 else "No Heatwave"


# Example prediction
result = predict_heatwave(
    max_temp=45,
    min_temp=31,
    humidity=50,
    wind_speed=7,
    previous_temp=44
)

print("Prediction:", result)

Prediction: Heatwave

In [ ]:
from flask import Flask, request, jsonify
import joblib
import threading

app = Flask(__name__)

model = joblib.load("heatwave_model.pkl")


@app.route("/predict", methods=["POST"])
def predict():

    data = request.json

    features = [[
        data["max_temp"],
        data["min_temp"],
        data["humidity"],
        data["wind_speed"],
        data["previous_temp"]
    ]]

    prediction = model.predict(features)[0]

    return jsonify({
        "prediction": "Heatwave" if prediction == 1 else "No Heatwave"
    })


def run_app():
    app.run(
        host="0.0.0.0",
        port=8000,
        use_reloader=False
    )


# Start Flask in background thread
flask_thread = threading.Thread(target=run_app)
flask_thread.start()

 * Serving Flask app '__main__'
 * Debug mode: off

INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://172.28.0.12:8000